Repository elastic/terraform-provider-ec, pull requests merged in 2020-09, with the labels that each got.

#55 ec_resource: Remove App Search support
  ec/acc/deployment_appsearch_test.go
  ec/acc/deployment_config_test.go
  ec/acc/deployment_destroy_test.go
  ec/acc/deployment_sweep_test.go
  ec/acc/testdata/deployment_appsearch.tf
  ec/acc/testdata/deployment_appsearch_top_config.tf
  ec/acc/testdata/deployment_appsearch_topology_config.tf
  ec/ecresource/deploymentresource/appsearchstate/appsearch_expanders.go
  ec/ecresource/deploymentresource/appsearchstate/appsearch_expanders_test.go
  ec/ecresource/deploymentresource/appsearchstate/appsearch_flatteners.go
  ec/ecresource/deploymentresource/appsearchstate/appsearch_flatteners_test.go
  ec/ecresource/deploymentresource/enterprisesearchstate/enterprise_search_expanders.go
  ec/ecresource/deploymentresource/expanders.go
  ec/ecresource/deploymentresource/expanders_test.go
  ec/ecresource/deploymentresource/flatteners.go
  ec/ecresource/deploymentresource/flatteners_test.go
  ec/ecresource/deploymentresource/schema.go
  ec/ecresource/deploymentresource/schema_appsearch.go
  ec/ecresource/deploymentresource/testutils.go
  examples/deployment_appsearch/README.md
  examples/deployment_appsearch/deployment.tf
Labels: breaking change

#57 ec_deployment: Support terraform import
  ec/acc/deployment_basic_test.go
  ec/ecresource/deploymentresource/resource.go
Labels: Team:Delivery, enhancement

#54 datasource: Implement new ec_deployment datasource
  docs/datasources/ec_deployment.md
  ec/acc/datasource_deployment_basic_test.go
  ec/acc/testdata/datasource_deployment_basic.tf
  ec/ecdatasource/deploymentdatasource/datasource.go
  ec/ecdatasource/deploymentdatasource/datasource_test.go
  ec/ecdatasource/deploymentdatasource/schema.go
  ec/ecdatasource/deploymentdatasource/schema_apm.go
  ec/ecdatasource/deploymentdatasource/schema_elasticsearch.go
  ec/ecdatasource/deploymentdatasource/schema_enterprise_search.go
  ec/ecdatasource/deploymentdatasource/schema_kibana.go
  ec/ecdatasource/deploymentdatasource/state/flatteners_apm.go
  ec/ecdatasource/deploymentdatasource/state/flatteners_apm_test.go
  ec/ecdatasource/deploymentdatasource/state/flatteners_elasticsearch.go
  ec/ecdatasource/deploymentdatasource/state/flatteners_elasticsearch_test.go
  ec/ecdatasource/deploymentdatasource/state/flatteners_enterprise_search.go
  ec/ecdatasource/deploymentdatasource/state/flatteners_enterprise_search_test.go
  ec/ecdatasource/deploymentdatasource/state/flatteners_kibana.go
  ec/ecdatasource/deploymentdatasource/state/flatteners_kibana_test.go
  ec/ecresource/deploymentresource/apmstate/apm_expanders.go
  ec/ecresource/deploymentresource/apmstate/apm_flatteners.go
  ec/ecresource/deploymentresource/elasticsearchstate/elasticsearch_expanders.go
  ec/ecresource/deploymentresource/elasticsearchstate/elasticsearch_flatteners.go
  ec/ecresource/deploymentresource/enterprisesearchstate/enterprise_search_expanders.go
  ec/ecresource/deploymentresource/enterprisesearchstate/enterprise_search_flatteners.go
  ec/ecresource/deploymentresource/kibanastate/kibana_expanders.go
  ec/ecresource/deploymentresource/kibanastate/kibana_flatteners.go
  ec/provider.go
  ec/util/cluster_endpoint_flatten.go
  ec/util/cluster_endpoint_flatten_test.go
  ec/util/parsers.go
  ec/util/parsers_test.go
  go.sum
Labels: enhancement

#62 ec_deployment:Delete Enterprise Search session_key
  ec/ecresource/deploymentresource/enterprisesearchstate/enterprise_search_expanders.go
  ec/ecresource/deploymentresource/enterprisesearchstate/enterprise_search_expanders_test.go
  ec/ecresource/deploymentresource/enterprisesearchstate/enterprise_search_flatteners.go
  ec/ecresource/deploymentresource/enterprisesearchstate/enterprise_search_flatteners_test.go
  ec/ecresource/deploymentresource/schema_enteprise_search.go
Labels: Team:Delivery, breaking change

#68 docs: Amend ec_deployment datasource match schema
  docs/datasources/ec_deployment.md
Labels: documentation

#61 ec_deployment: Remove APM secret_token from config
  ec/acc/deployment_basic_test.go
  ec/acc/deployment_config_test.go
  ec/ecresource/deploymentresource/apmstate/apm_expanders.go
  ec/ecresource/deploymentresource/apmstate/apm_expanders_test.go
  ec/ecresource/deploymentresource/apmstate/apm_flatteners.go
  ec/ecresource/deploymentresource/apmstate/apm_flatteners_test.go
  ec/ecresource/deploymentresource/flatteners.go
  ec/ecresource/deploymentresource/flatteners_test.go
  ec/ecresource/deploymentresource/schema.go
  ec/ecresource/deploymentresource/schema_apm.go
  examples/deployment/deployment.tf
Labels: Team:Delivery, breaking change, enhancement

#65 ec_deployment: Add config block to elasticsearch
  docs/datasources/ec_deployment.md
  docs/resources/ec_deployment.md
  ec/acc/deployment_basic_test.go
  ec/acc/testdata/deployment_basic_top_config.tf
  ec/acc/testdata/deployment_basic_topology_config.tf
  ec/ecresource/deploymentresource/deploymentstate/traffic_filter.go
  ec/ecresource/deploymentresource/elasticsearchstate/elasticsearch_expanders.go
  ec/ecresource/deploymentresource/elasticsearchstate/elasticsearch_expanders_test.go
  ec/ecresource/deploymentresource/elasticsearchstate/elasticsearch_flatteners.go
  ec/ecresource/deploymentresource/elasticsearchstate/elasticsearch_flatteners_test.go
  ec/ecresource/deploymentresource/expanders_test.go
  ec/ecresource/deploymentresource/flatteners_test.go
  ec/ecresource/deploymentresource/schema.go
  ec/ecresource/deploymentresource/schema_elasticsearch.go
  ec/ecresource/deploymentresource/testutils.go
  ec/util/set_util.go
  ec/util/set_util_test.go
Labels: Team:Delivery, enhancement

#75 acc: Update basic test to pass after latest commit
  ec/acc/deployment_basic_test.go
Labels: acceptance

#71 ec_deployment: Remove display_name attribute
  ec/ecresource/deploymentresource/apmstate/apm_expanders.go
  ec/ecresource/deploymentresource/apmstate/apm_expanders_test.go
  ec/ecresource/deploymentresource/apmstate/apm_flatteners.go
  ec/ecresource/deploymentresource/apmstate/apm_flatteners_test.go
  ec/ecresource/deploymentresource/elasticsearchstate/elasticsearch_expanders.go
  ec/ecresource/deploymentresource/elasticsearchstate/elasticsearch_expanders_test.go
  ec/ecresource/deploymentresource/elasticsearchstate/elasticsearch_flatteners.go
  ec/ecresource/deploymentresource/elasticsearchstate/elasticsearch_flatteners_test.go
  ec/ecresource/deploymentresource/enterprisesearchstate/enterprise_search_expanders.go
  ec/ecresource/deploymentresource/enterprisesearchstate/enterprise_search_expanders_test.go
  ec/ecresource/deploymentresource/enterprisesearchstate/enterprise_search_flatteners.go
  ec/ecresource/deploymentresource/enterprisesearchstate/enterprise_search_flatteners_test.go
  ec/ecresource/deploymentresource/expanders_test.go
  ec/ecresource/deploymentresource/kibanastate/kibana_expanders.go
  ec/ecresource/deploymentresource/kibanastate/kibana_expanders_test.go
  ec/ecresource/deploymentresource/kibanastate/kibana_flatteners.go
  ec/ecresource/deploymentresource/kibanastate/kibana_flatteners_test.go
  ec/ecresource/deploymentresource/schema_apm.go
  ec/ecresource/deploymentresource/schema_elasticsearch.go
  ec/ecresource/deploymentresource/schema_enteprise_search.go
  ec/ecresource/deploymentresource/schema_kibana.go
  ec/ecresource/deploymentresource/testutils.go
Labels: breaking change

#83 ci: Add jenkins jjbb job definitions
  .ci/Makefile
  .ci/jobs/defaults.yml
  .ci/jobs/elastic+terraform-provider-ec+master.yml
  .ci/jobs/elastic+terraform-provider-ec+pull-request.yml
  .ci/pipelines/acceptance.Jenkinsfile
  .ci/views/view.yml
  .gitignore
  build/Makefile.test
  scripts/retry.sh
Labels: Team:Delivery, acceptance

#82 ci: Add terraform fmt to lint and format targets
  build/Makefile.format
  build/Makefile.lint
  build/Makefile.test
Labels: Team:Delivery, enhancement

#81 Add traffic_filter_association resource
  docs/resources/ec_deployment_traffic_filter.md
  docs/resources/ec_deployment_traffic_filter_association.md
  ec/acc/deployment_traffic_filter_association_test.go
  ec/acc/testdata/deployment_traffic_filter_association_basic.tf
  ec/acc/testdata/deployment_traffic_filter_association_basic_update.tf
  ec/ecresource/trafficfilterassocresource/create.go
  ec/ecresource/trafficfilterassocresource/delete.go
  ec/ecresource/trafficfilterassocresource/expanders.go
  ec/ecresource/trafficfilterassocresource/expanders_test.go
  ec/ecresource/trafficfilterassocresource/flatteners.go
  ec/ecresource/trafficfilterassocresource/flatteners_test.go
  ec/ecresource/trafficfilterassocresource/read.go
  ec/ecresource/trafficfilterassocresource/resource.go
  ec/ecresource/trafficfilterassocresource/schema.go
  ec/ecresource/trafficfilterassocresource/testutils.go
  ec/provider.go
Labels: Team:Delivery, new-resource

#86 ci: Fix broken acceptance build pipeline
  .ci/Makefile
  .ci/pipelines/acceptance.Jenkinsfile
  .github/workflows/acceptance.yml
Labels: Team:Delivery

#85 ec_stack: Add Data Source
  docs/datasources/ec_stack.md
  ec/acc/datasource_stack_test.go
  ec/acc/testdata/datasource_stack_latest.tf
  ec/acc/testdata/datasource_stack_regex.tf
  ec/ecdatasource/stackdatasource/datasource.go
  ec/ecdatasource/stackdatasource/datasource_test.go
  ec/ecdatasource/stackdatasource/schema.go
  ec/ecdatasource/stackdatasource/state/flatteners_apm.go
  ec/ecdatasource/stackdatasource/state/flatteners_apm_test.go
  ec/ecdatasource/stackdatasource/state/flatteners_elasticsearch.go
  ec/ecdatasource/stackdatasource/state/flatteners_elasticsearch_test.go
  ec/ecdatasource/stackdatasource/state/flatteners_enterprise_search.go
  ec/ecdatasource/stackdatasource/state/flatteners_enterprise_search_test.go
  ec/ecdatasource/stackdatasource/state/flatteners_kibana.go
  ec/ecdatasource/stackdatasource/state/flatteners_kibana_test.go
  ec/provider.go
  go.sum
Labels: Team:Delivery, new-data-source

#87 doc: Complete ec_deployment attributes and help
  docs/limitations.md
  docs/resources/ec_deployment.md
  ec/ecresource/deploymentresource/schema_apm.go
Labels: documentation

#88 ec_deployments: New datasource
  docs/data-sources/ec_deployment.md
  docs/data-sources/ec_deployments.md
  docs/data-sources/ec_stack.md
  ec/acc/datasource_deployment_basic_test.go
  ec/acc/testdata/datasource_deployment_basic.tf
  ec/ecdatasource/deploymentsdatasource/datasource.go
  ec/ecdatasource/deploymentsdatasource/datasource_test.go
  ec/ecdatasource/deploymentsdatasource/expanders.go
  ec/ecdatasource/deploymentsdatasource/expanders_test.go
  ec/ecdatasource/deploymentsdatasource/schema.go
  ec/provider.go
Labels: enhancement, new-data-source

#90 ec_deployment: Refactor datasource to use diagnostics
  ec/ecdatasource/deploymentdatasource/datasource.go
Labels: Refactor / Internal

#92 acceptance: Refactor traffic filter tests to use trafficfilterapi
  ec/acc/deployment_traffic_filter_checks_test.go
  ec/acc/deployment_traffic_filter_destroy_test.go
  ec/acc/deployment_traffic_filter_sweep_test.go
Labels: Refactor / Internal, acceptance

#91 ec_deployment: Display traffic filters on datasource
  docs/data-sources/ec_deployment.md
  ec/ecdatasource/deploymentdatasource/datasource.go
  ec/ecdatasource/deploymentdatasource/schema.go
  ec/ecdatasource/deploymentdatasource/state/flatteners_traffic_filter.go
  ec/ecdatasource/deploymentdatasource/state/flatteners_traffic_filter_test.go
Labels: enhancement

#95 acceptance: Update ec_deployment datasource test to include traffic filter
  ec/acc/datasource_deployment_basic_test.go
  ec/acc/testdata/datasource_deployment_basic.tf
Labels: acceptance

#97 docs: Contributing documentation
  CONTRIBUTING.md
  README.md
  build/Makefile.test
Labels: documentation

#103 misc: Unexport functions that are meant to be internal
  ec/acc/deployment_checks_test.go
  ec/acc/deployment_destroy_test.go
  ec/acc/deployment_sweep_test.go
  ec/acc/deployment_traffic_filter_checks_test.go
  ec/acc/deployment_traffic_filter_destroy_test.go
  ec/acc/deployment_traffic_filter_sweep_test.go
  ec/acc/sweep_test.go
  ec/ecresource/deploymentresource/flatteners_test.go
  ec/ecresource/deploymentresource/resource.go
  ec/ecresource/deploymentresource/schema.go
  ec/ecresource/deploymentresource/schema_apm.go
  ec/ecresource/deploymentresource/schema_elasticsearch.go
  ec/ecresource/deploymentresource/schema_enteprise_search.go
  ec/ecresource/deploymentresource/schema_kibana.go
  ec/ecresource/trafficfilterassocresource/resource.go
  ec/ecresource/trafficfilterassocresource/schema.go
  ec/ecresource/trafficfilterassocresource/testutils.go
  ec/ecresource/trafficfilterresource/flatteners_test.go
  ec/ecresource/trafficfilterresource/resource.go
  ec/ecresource/trafficfilterresource/schema.go
  ec/ecresource/trafficfilterresource/testutils.go
Labels: Refactor / Internal

#104 ci: Do not cancel builds on commit push
  .ci/jobs/elastic+terraform-provider-ec+pull-request.yml
Labels: Refactor / Internal
