Repository elastic/terraform-provider-ec, pull requests merged in 2020-12, with the labels that each got.

#188 ec_deployment: Note on importing with user settings (config)
  docs/resources/ec_deployment.md
Labels: documentation

#190 ec_deployment: Allow for ES node types to be editable
  docs/resources/ec_deployment.md
  ec/acc/deployment_basic_defaults_test.go
  ec/acc/testdata/deployment_basic_defaults_3.tf
  ec/ecresource/deploymentresource/elasticsearch_expanders.go
  ec/ecresource/deploymentresource/elasticsearch_expanders_test.go
  ec/ecresource/deploymentresource/elasticsearch_flatteners.go
  ec/ecresource/deploymentresource/elasticsearch_flatteners_test.go
  ec/ecresource/deploymentresource/expanders_test.go
  ec/ecresource/deploymentresource/flatteners_test.go
  ec/ecresource/deploymentresource/schema_elasticsearch.go
  ec/ecresource/deploymentresource/testutil_datastruct.go
Labels: enhancement

#195 data ec_deployments: Change ID generation to hashing
  ec/acc/datasource_deployment_basic_test.go
  ec/acc/testdata/datasource_deployment_basic.tf
  ec/ecdatasource/deploymentsdatasource/datasource.go
  ec/ecdatasource/deploymentsdatasource/datasource_test.go
Labels: acceptance, enhancement

#194 all: Treat 404 and some 403 as resource destroyed
  ec/ecresource/deploymentresource/delete.go
  ec/ecresource/deploymentresource/delete_test.go
  ec/ecresource/deploymentresource/flatteners.go
  ec/ecresource/deploymentresource/flatteners_test.go
  ec/ecresource/deploymentresource/read.go
  ec/ecresource/deploymentresource/read_test.go
  ec/ecresource/deploymentresource/update_traffic_rules.go
  ec/ecresource/trafficfilterassocresource/delete.go
  ec/ecresource/trafficfilterassocresource/delete_test.go
  ec/ecresource/trafficfilterassocresource/read.go
  ec/ecresource/trafficfilterassocresource/read_test.go
  ec/ecresource/trafficfilterresource/delete.go
  ec/ecresource/trafficfilterresource/delete_test.go
  ec/ecresource/trafficfilterresource/read.go
  ec/ecresource/trafficfilterresource/read_test.go
  ec/internal/util/traffic_filter_err.go
  ec/internal/util/traffic_filter_err_test.go
  go.mod
  go.sum
Labels: Team:Delivery, bug

#196 release: Add goreleaser config and github action
  .github/workflows/release.yml
  .gitignore
  .goreleaser.yml
  Makefile
  README.md
  build/Makefile.deps
  build/Makefile.release
  docs/index.md
  ec/acc/testdata/deployment_basic_defaults_3.tf
  ec/version.go
  examples/deployment/deployment.tf
  examples/deployment_ccs/deployment.tf
  examples/deployment_ec2_instance/provider.tf
  examples/deployment_with_init/provider.tf
Labels: Team:Delivery

#163 Add Terraform provider docs content
  docs-elastic/index.asciidoc
Labels: documentation

#197 mod: Update cloud-sdk-go to fix stack list sort
  go.mod
  go.sum
Labels: Team:Delivery, bug

#198 Add beta header to the Elastic docs
  docs-elastic/page_header.html
Labels: documentation

#199 release: Remove release GitHub action
  .github/workflows/release.yml
Labels: Team:Delivery

#202 release: Add Jenkins release job and file
  .ci/.env
  .ci/Makefile
  .ci/jobs/elastic+terraform-provider-ec+tag.yml
  .ci/pipelines/release.Jenkinsfile
  .gitignore
  build/Makefile.release
Labels: Refactor / Internal, Team:Delivery

#205 testacc: Sweep all existing 1h+ old deployments
  ec/acc/deployment_sweep_test.go
  ec/acc/deployment_sweep_test_test.go
Labels: Team:Delivery, acceptance
