Repository elastic/terraform-provider-ec, pull requests merged in 2020-08, with the labels that each got.

#33 mod: Update terraform-plugin-sdk to version v2
  ec/acc/acc_prereq.go
  ec/acc/deployment_destroy_test.go
  ec/acc/deployment_sweep_test.go
  ec/acc/deployment_test.go
  ec/acc/sweep_test.go
  ec/acc/testdata/deployment_appsearch.tf
  ec/acc/testdata/deployment_basic.tf
  ec/ecresource/deployment.go
  ec/ecresource/deploymentresource/create.go
  ec/ecresource/deploymentresource/delete.go
  ec/ecresource/deploymentresource/expanders.go
  ec/ecresource/deploymentresource/expanders_test.go
  ec/ecresource/deploymentresource/flatteners.go
  ec/ecresource/deploymentresource/flatteners_test.go
  ec/ecresource/deploymentresource/read.go
  ec/ecresource/deploymentresource/schema.go
  ec/ecresource/deploymentresource/testutils.go
  ec/ecresource/deploymentresource/update.go
  ec/ecresource/deploymentresource/wait.go
  ec/provider.go
  ec/provider_config.go
  go.mod
  go.sum
  main.go
Labels: Team:Delivery, enhancement

#39 misc: Only accept EC_API_KEY as the API key environment variable
  README.md
  docs/index.md
  ec/acc/acc_prereq.go
  ec/acc/sweep_test.go
  ec/provider.go
Labels: Team:Delivery, breaking change

#35 provider: Use ConfigureContextFunc
  .gitignore
  ec/provider.go
  ec/provider_config.go
Labels: enhancement

#37 deploymentresource: Add support for EnterpriseSearch resource type
  ec/acc/deployment_test.go
  ec/acc/testdata/deployment_enterprise_search.tf
  ec/ecresource/deploymentresource/enterprisesearchstate/enterprise_search_expanders.go
  ec/ecresource/deploymentresource/enterprisesearchstate/enterprise_search_expanders_test.go
  ec/ecresource/deploymentresource/enterprisesearchstate/enterprise_search_flatteners.go
  ec/ecresource/deploymentresource/enterprisesearchstate/enterprise_search_flatteners_test.go
  ec/ecresource/deploymentresource/expanders.go
  ec/ecresource/deploymentresource/expanders_test.go
  ec/ecresource/deploymentresource/flatteners.go
  ec/ecresource/deploymentresource/flatteners_test.go
  ec/ecresource/deploymentresource/schema.go
  ec/ecresource/deploymentresource/testutils.go
  examples/deployment_enterprise_search/README.md
  examples/deployment_enterprise_search/deployment.tf
  go.sum
Labels: Team:Delivery, enhancement

#45 terraform: Add support for 0.13 version
  README.md
  build/Makefile.build
  examples/deployment/deployment.tf
  examples/deployment_appsearch/deployment.tf
  examples/deployment_enterprise_search/deployment.tf
  examples/deployment_monitoring/README.md
  examples/deployment_monitoring/deployment.tf
Labels: documentation, enhancement

#46 ci: Add validate-examples target in action run
  .github/workflows/go.yml
  README.md
  build/Makefile.lint
  scripts/validate_examples.sh
Labels: enhancement

#50 acc: Remove deployment.Healthy check
  ec/acc/deployment_checks_test.go
Labels: Team:Delivery, acceptance

#51 acceptance: Add Enterprise Search to basic tests and remove es specific tests
  ec/acc/deployment_basic_test.go
  ec/acc/deployment_config_test.go
  ec/acc/deployment_enterprise_search_test.go
  ec/acc/testdata/deployment_basic.tf
  ec/acc/testdata/deployment_basic_top_config.tf
  ec/acc/testdata/deployment_basic_topology_config.tf
  ec/acc/testdata/deployment_enterprise_search.tf
  ec/acc/testdata/deployment_enterprise_search_top_config.tf
  ec/acc/testdata/deployment_enterprise_search_topology_config.tf
Labels: Team:Delivery, acceptance
