Repository elastic/terraform-provider-ec, pull requests merged in 2020-10, with the labels that each got.

#98 ec_resource: Use deployment template as blueprint
  .gitignore
  README.md
  docs/resources/ec_deployment.md
  ec/acc/deployment_basic_defaults_test.go
  ec/acc/deployment_basic_test.go
  ec/acc/deployment_config_test.go
  ec/acc/testdata/deployment_basic_defaults_1.tf
  ec/acc/testdata/deployment_basic_defaults_2.tf
  ec/acc/testdata/deployment_basic_defaults_3.tf
  ec/acc/testdata/deployment_basic_defaults_4.tf
  ec/acc/testdata/deployment_basic_top_config.tf
  ec/acc/testdata/deployment_basic_topology_config.tf
  ec/ecresource/deploymentresource/apm_expanders.go
  ec/ecresource/deploymentresource/apm_expanders_test.go
  ec/ecresource/deploymentresource/apm_flatteners.go
  ec/ecresource/deploymentresource/apm_flatteners_test.go
  ec/ecresource/deploymentresource/create.go
  ec/ecresource/deploymentresource/delete.go
  ec/ecresource/deploymentresource/elasticsearch_expanders.go
  ec/ecresource/deploymentresource/elasticsearch_expanders_test.go
  ec/ecresource/deploymentresource/elasticsearch_flatteners.go
  ec/ecresource/deploymentresource/elasticsearch_flatteners_test.go
  ec/ecresource/deploymentresource/enterprise_search_expanders.go
  ec/ecresource/deploymentresource/enterprise_search_expanders_test.go
  ec/ecresource/deploymentresource/enterprise_search_flatteners.go
  ec/ecresource/deploymentresource/enterprise_search_flatteners_test.go
  ec/ecresource/deploymentresource/expanders.go
  ec/ecresource/deploymentresource/expanders_test.go
  ec/ecresource/deploymentresource/flatteners_test.go
  ec/ecresource/deploymentresource/kibana_expanders.go
  ec/ecresource/deploymentresource/kibana_expanders_test.go
  ec/ecresource/deploymentresource/kibana_flatteners.go
  ec/ecresource/deploymentresource/kibana_flatteners_test.go
  ec/ecresource/deploymentresource/read.go
  ec/ecresource/deploymentresource/resource.go
  ec/ecresource/deploymentresource/schema.go
  ec/ecresource/deploymentresource/schema_apm.go
  ec/ecresource/deploymentresource/schema_elasticsearch.go
  ec/ecresource/deploymentresource/schema_enteprise_search.go
  ec/ecresource/deploymentresource/schema_kibana.go
  ec/ecresource/deploymentresource/stopped_resource.go
  ec/ecresource/deploymentresource/stopped_resource_test.go
  ec/ecresource/deploymentresource/testdata/aws-hot-warm-v2.json
  ec/ecresource/deploymentresource/testdata/aws-io-optimized-v2.json
  ec/ecresource/deploymentresource/testutil_datastruct.go
  ec/ecresource/deploymentresource/testutil_func.go
  ec/ecresource/deploymentresource/testutil_func_test.go
  ec/ecresource/deploymentresource/update.go
  ec/internal/util/parsers.go
  examples/deployment/deployment.tf
  go.sum
Labels: Team:Delivery, breaking change, enhancement

#112 ec_resource: Fix overwritten elasticsearch config
  ec/acc/deployment_hotwarm_test.go
  ec/acc/testdata/deployment_hotwarm_1.tf
  ec/acc/testdata/deployment_hotwarm_2.tf
  ec/ecresource/deploymentresource/elasticsearch_expanders.go
  ec/ecresource/deploymentresource/elasticsearch_expanders_test.go
Labels: Team:Delivery, bug

#115 dependencies: Update terraform-plugin-sdk to v2.0.4
  ec/acc/datasource_deployment_basic_test.go
  go.mod
  go.sum
Labels: Refactor / Internal

#117 version: Add "-dev" suffix to committed version
  Makefile
  ec/version.go
  gen/gen.go
Labels: Refactor / Internal, Team:Delivery, enhancement

#119 api client: Enable HTTP retries on timeout
  ec/provider_config.go
  go.mod
  go.sum
Labels: Team:Delivery, enhancement

#120 acceptance: Improve ec_deployments datasource query test
  ec/acc/datasource_deployment_basic_test.go
  ec/acc/testdata/datasource_deployment_basic.tf
Labels: acceptance

#118 config: Add verbose_ credentials and file setting
  docs/index.md
  ec/provider.go
  ec/provider_config.go
  ec/provider_config_test.go
Labels: Team:Delivery, enhancement

#114 ec_deployment: rename memory_per_node to size
  docs/data-sources/ec_deployment.md
  docs/resources/ec_deployment.md
  ec/acc/datasource_deployment_basic_test.go
  ec/acc/deployment_basic_defaults_test.go
  ec/acc/deployment_basic_test.go
  ec/acc/deployment_hotwarm_test.go
  ec/acc/testdata/datasource_deployment_basic.tf
  ec/acc/testdata/deployment_basic.tf
  ec/acc/testdata/deployment_basic_defaults_2.tf
  ec/acc/testdata/deployment_basic_defaults_3.tf
  ec/acc/testdata/deployment_basic_top_config.tf
  ec/acc/testdata/deployment_basic_topology_config.tf
  ec/acc/testdata/deployment_basic_with_traffic_filter.tf
  ec/acc/testdata/deployment_basic_with_traffic_filter_update.tf
  ec/acc/testdata/deployment_hotwarm_2.tf
  ec/acc/testdata/deployment_traffic_filter_association_basic.tf
  ec/acc/testdata/deployment_traffic_filter_association_basic_update.tf
  ec/ecdatasource/deploymentdatasource/flatteners_apm.go
  ec/ecdatasource/deploymentdatasource/flatteners_apm_test.go
  ec/ecdatasource/deploymentdatasource/flatteners_elasticsearch.go
  ec/ecdatasource/deploymentdatasource/flatteners_elasticsearch_test.go
  ec/ecdatasource/deploymentdatasource/flatteners_enterprise_search.go
  ec/ecdatasource/deploymentdatasource/flatteners_enterprise_search_test.go
  ec/ecdatasource/deploymentdatasource/flatteners_kibana.go
  ec/ecdatasource/deploymentdatasource/flatteners_kibana_test.go
  ec/ecdatasource/deploymentdatasource/schema_apm.go
  ec/ecdatasource/deploymentdatasource/schema_elasticsearch.go
  ec/ecdatasource/deploymentdatasource/schema_enterprise_search.go
  ec/ecdatasource/deploymentdatasource/schema_kibana.go
  ec/ecresource/deploymentresource/apm_expanders_test.go
  ec/ecresource/deploymentresource/apm_flatteners.go
  ec/ecresource/deploymentresource/apm_flatteners_test.go
  ec/ecresource/deploymentresource/elasticsearch_expanders.go
  ec/ecresource/deploymentresource/elasticsearch_expanders_test.go
  ec/ecresource/deploymentresource/elasticsearch_flatteners.go
  ec/ecresource/deploymentresource/elasticsearch_flatteners_test.go
  ec/ecresource/deploymentresource/enterprise_search_expanders_test.go
  ec/ecresource/deploymentresource/enterprise_search_flatteners.go
  ec/ecresource/deploymentresource/enterprise_search_flatteners_test.go
  ec/ecresource/deploymentresource/kibana_expanders.go
  ec/ecresource/deploymentresource/kibana_expanders_test.go
  ec/ecresource/deploymentresource/kibana_flatteners.go
  ec/ecresource/deploymentresource/kibana_flatteners_test.go
  ec/ecresource/deploymentresource/schema_apm.go
  ec/ecresource/deploymentresource/schema_elasticsearch.go
  ec/ecresource/deploymentresource/schema_enteprise_search.go
  ec/ecresource/deploymentresource/schema_kibana.go
  ec/ecresource/deploymentresource/testutil_datastruct.go
  ec/internal/util/parsers.go
  ec/internal/util/parsers_test.go
  examples/deployment/deployment.tf
Labels: Team:Delivery, breaking change, enhancement

#121 acceptance: Make test fields dynamic
  build/Makefile.test
  ec/acc/acc_prereq.go
  ec/acc/datasource_deployment_basic_test.go
  ec/acc/datasource_stack_test.go
  ec/acc/deployment_basic_defaults_test.go
  ec/acc/deployment_basic_test.go
  ec/acc/deployment_checks_test.go
  ec/acc/deployment_config_test.go
  ec/acc/deployment_destroy_test.go
  ec/acc/deployment_hotwarm_test.go
  ec/acc/deployment_sweep_test.go
  ec/acc/deployment_traffic_filter_association_test.go
  ec/acc/deployment_traffic_filter_checks_test.go
  ec/acc/deployment_traffic_filter_destroy_test.go
  ec/acc/deployment_traffic_filter_sweep_test.go
  ec/acc/deployment_traffic_filter_test.go
  ec/acc/sweep_test.go
  ec/acc/testdata/datasource_deployment_basic.tf
  ec/acc/testdata/deployment_basic.tf
  ec/acc/testdata/deployment_basic_defaults_1.tf
  ec/acc/testdata/deployment_basic_defaults_2.tf
  ec/acc/testdata/deployment_basic_defaults_3.tf
  ec/acc/testdata/deployment_basic_defaults_4.tf
  ec/acc/testdata/deployment_basic_top_config.tf
  ec/acc/testdata/deployment_basic_topology_config.tf
  ec/acc/testdata/deployment_basic_with_traffic_filter.tf
  ec/acc/testdata/deployment_basic_with_traffic_filter_update.tf
  ec/acc/testdata/deployment_hotwarm_1.tf
  ec/acc/testdata/deployment_hotwarm_2.tf
  ec/acc/testdata/deployment_traffic_filter_association_basic.tf
  ec/acc/testdata/deployment_traffic_filter_association_basic_update.tf
Labels: acceptance

#122 examples: Add example used in the ElasticON presentation
  examples/deployment_with_init/README.md
  examples/deployment_with_init/deployment.tf
  examples/deployment_with_init/es_config.sh
  examples/deployment_with_init/main.tf
  examples/deployment_with_init/provider.tf
Labels: documentation

#126 ec_deployment: Fix broken user_settings_json field
  ec/acc/deployment_basic_test.go
  ec/acc/testdata/deployment_basic_top_config.tf
  ec/acc/testdata/deployment_basic_topology_config.tf
  ec/ecresource/deploymentresource/apm_expanders.go
  ec/ecresource/deploymentresource/apm_expanders_test.go
  ec/ecresource/deploymentresource/apm_flatteners.go
  ec/ecresource/deploymentresource/apm_flatteners_test.go
  ec/ecresource/deploymentresource/elasticsearch_expanders.go
  ec/ecresource/deploymentresource/elasticsearch_expanders_test.go
  ec/ecresource/deploymentresource/elasticsearch_flatteners.go
  ec/ecresource/deploymentresource/elasticsearch_flatteners_test.go
  ec/ecresource/deploymentresource/enterprise_search_expanders.go
  ec/ecresource/deploymentresource/enterprise_search_expanders_test.go
  ec/ecresource/deploymentresource/enterprise_search_flatteners.go
  ec/ecresource/deploymentresource/enterprise_search_flatteners_test.go
  ec/ecresource/deploymentresource/expanders_test.go
  ec/ecresource/deploymentresource/flatteners.go
  ec/ecresource/deploymentresource/flatteners_test.go
  ec/ecresource/deploymentresource/kibana_expanders.go
  ec/ecresource/deploymentresource/kibana_expanders_test.go
  ec/ecresource/deploymentresource/kibana_flatteners.go
  ec/ecresource/deploymentresource/kibana_flatteners_test.go
  ec/ecresource/deploymentresource/testdata/deployment-aws-ccs.json
  ec/ecresource/deploymentresource/testdata/deployment-aws-io-optimized.json
  ec/ecresource/deploymentresource/testdata/deployment-azure-io-optimized.json
  ec/ecresource/deploymentresource/testdata/deployment-gcp-hot-warm.json
  ec/ecresource/deploymentresource/testdata/deployment-gcp-io-optimized.json
  ec/ecresource/deploymentresource/testutil_datastruct.go
  ec/ecresource/deploymentresource/testutil_func.go
Labels: Refactor / Internal, Team:Delivery, bug

#128 config: Reduce timeout to 40s
  ec/provider.go
  ec/provider_config_test.go
Labels: Refactor / Internal, enhancement

#127 docs: Add note on importing legacy deployments
  docs/resources/ec_deployment.md
Labels: documentation

#135 ec_resource: Fix panic on empty DT resource kind
  ec/acc/deployment_ccs_test.go
  ec/acc/deployment_config_test.go
  ec/acc/testdata/deployment_basic_top_config.tf
  ec/acc/testdata/deployment_basic_topology_config.tf
  ec/acc/testdata/deployment_ccs_1.tf
  ec/acc/testdata/deployment_ccs_2.tf
  ec/ecresource/deploymentresource/apm_expanders.go
  ec/ecresource/deploymentresource/elasticsearch_expanders.go
  ec/ecresource/deploymentresource/enterprise_search_expanders.go
  ec/ecresource/deploymentresource/expanders_test.go
  ec/ecresource/deploymentresource/kibana_expanders.go
  ec/ecresource/deploymentresource/testdata/aws-cross-cluster-search-v2.json
  ec/ecresource/deploymentresource/testdata/empty-deployment_template.json
  ec/ecresource/deploymentresource/testutil_func.go
Labels: bug

#139 misc: Documentation ownership for cloud writers
  .github/CODEOWNERS
Labels: documentation

#141 acceptance: Remove acceptance build tag
  build/Makefile.test
  ec/acc/acc_prereq.go
  ec/acc/datasource_deployment_basic_test.go
  ec/acc/datasource_stack_test.go
  ec/acc/deployment_basic_defaults_test.go
  ec/acc/deployment_basic_test.go
  ec/acc/deployment_ccs_test.go
  ec/acc/deployment_checks_test.go
  ec/acc/deployment_config_test.go
  ec/acc/deployment_destroy_test.go
  ec/acc/deployment_hotwarm_test.go
  ec/acc/deployment_sweep_test.go
  ec/acc/deployment_traffic_filter_association_test.go
  ec/acc/deployment_traffic_filter_checks_test.go
  ec/acc/deployment_traffic_filter_destroy_test.go
  ec/acc/deployment_traffic_filter_sweep_test.go
  ec/acc/deployment_traffic_filter_test.go
  ec/acc/sweep_test.go
Labels: acceptance, enhancement

#140 ec_deployment: Add remote_cluster to Elasticsearch
  docs/resources/ec_deployment.md
  ec/acc/acc_prereq.go
  ec/acc/deployment_ccs_test.go
  ec/acc/sweep_test.go
  ec/acc/testdata/deployment_ccs_1.tf
  ec/ecresource/deploymentresource/create.go
  ec/ecresource/deploymentresource/elasticsearch_flatteners.go
  ec/ecresource/deploymentresource/elasticsearch_flatteners_test.go
  ec/ecresource/deploymentresource/elasticsearch_remote_cluster_expanders.go
  ec/ecresource/deploymentresource/elasticsearch_remote_cluster_expanders_test.go
  ec/ecresource/deploymentresource/flatteners.go
  ec/ecresource/deploymentresource/flatteners_test.go
  ec/ecresource/deploymentresource/read.go
  ec/ecresource/deploymentresource/schema_elasticsearch.go
  ec/ecresource/deploymentresource/update.go
  ec/ecresource/deploymentresource/wait.go
  ec/provider_config.go
  ec/provider_config_test.go
  examples/deployment_ccs/README.md
  examples/deployment_ccs/deployment.tf
  examples/deployment_ccs/outputs.tf
  go.mod
  go.sum
Labels: Team:Delivery, enhancement

#138 ec_deployment: Add observability settings
  docs/resources/ec_deployment.md
  ec/acc/deployment_observability_test.go
  ec/acc/testdata/deployment_observability_1.tf
  ec/acc/testdata/deployment_observability_2.tf
  ec/acc/testdata/deployment_observability_3.tf
  ec/acc/testdata/deployment_observability_4.tf
  ec/ecresource/deploymentresource/elasticsearch_expanders.go
  ec/ecresource/deploymentresource/elasticsearch_expanders_test.go
  ec/ecresource/deploymentresource/elasticsearch_flatteners.go
  ec/ecresource/deploymentresource/elasticsearch_flatteners_test.go
  ec/ecresource/deploymentresource/expanders.go
  ec/ecresource/deploymentresource/expanders_test.go
  ec/ecresource/deploymentresource/flatteners.go
  ec/ecresource/deploymentresource/flatteners_test.go
  ec/ecresource/deploymentresource/observability.go
  ec/ecresource/deploymentresource/observability_test.go
  ec/ecresource/deploymentresource/schema.go
  ec/ecresource/deploymentresource/schema_elasticsearch.go
  ec/ecresource/deploymentresource/testutil_datastruct.go
Labels: enhancement

#146 acceptance: Create tests for all deployment templates
  ec/acc/datasource_deployment_basic_test.go
  ec/acc/deployment_ccs_test.go
  ec/acc/deployment_compute_optimized_test.go
  ec/acc/deployment_config_test.go
  ec/acc/deployment_enterprise_search_test.go
  ec/acc/deployment_memory_optimized_test.go
  ec/acc/deployment_observability_tpl_test.go
  ec/acc/deployment_security_test.go
  ec/acc/testdata/deployment_compute_optimized_1.tf
  ec/acc/testdata/deployment_compute_optimized_2.tf
  ec/acc/testdata/deployment_enterprise_search_1.tf
  ec/acc/testdata/deployment_enterprise_search_2.tf
  ec/acc/testdata/deployment_memory_optimized_1.tf
  ec/acc/testdata/deployment_memory_optimized_2.tf
  ec/acc/testdata/deployment_observability_tpl_1.tf
  ec/acc/testdata/deployment_observability_tpl_2.tf
  ec/acc/testdata/deployment_security_1.tf
  ec/acc/testdata/deployment_security_2.tf
  go.mod
  go.sum
Labels: acceptance

#151 acceptance: Set parallel tests to 4
  build/Makefile.test
  ec/ecresource/trafficfilterassocresource/resource.go
  ec/ecresource/trafficfilterresource/resource.go
  go.mod
  go.sum
Labels: acceptance

#149 ec_deployment: Add observability settings to datasource
  docs/data-sources/ec_deployment.md
  docs/resources/ec_deployment.md
  ec/acc/datasource_deployment_basic_test.go
  ec/acc/testdata/datasource_deployment_basic.tf
  ec/ecdatasource/deploymentdatasource/datasource.go
  ec/ecdatasource/deploymentdatasource/datasource_test.go
  ec/ecdatasource/deploymentdatasource/flatteners_observability.go
  ec/ecdatasource/deploymentdatasource/flatteners_observability_test.go
  ec/ecdatasource/deploymentdatasource/schema.go
Labels: enhancement

#153 acceptance: Split long tests into multiple tests
  ec/acc/deployment_basic_defaults_test.go
  ec/acc/deployment_basic_test.go
  ec/acc/testdata/deployment_basic_defaults_hw.tf
  ec/acc/testdata/deployment_basic_topology_config_2.tf
  ec/acc/testdata/deployment_basic_topology_config_3.tf
  ec/acc/testdata/deployment_basic_with_traffic_filter_2.tf
  ec/acc/testdata/deployment_basic_with_traffic_filter_3.tf
Labels: acceptance

#155 ec_deployment: Fix panic on invalid resource types
  docs/resources/ec_deployment.md
  ec/acc/deployment_basic_defaults_test.go
  ec/acc/testdata/deployment_basic_defaults_3.tf
  ec/acc/testdata/deployment_basic_defaults_hw.tf
  ec/ecdatasource/deploymentdatasource/datasource_test.go
  ec/ecdatasource/deploymentsdatasource/datasource_test.go
  ec/ecdatasource/deploymentsdatasource/expanders_test.go
  ec/ecdatasource/stackdatasource/datasource_test.go
  ec/ecresource/deploymentresource/apm_expanders.go
  ec/ecresource/deploymentresource/apm_expanders_test.go
  ec/ecresource/deploymentresource/elasticsearch_remote_cluster_expanders_test.go
  ec/ecresource/deploymentresource/enterprise_search_expanders.go
  ec/ecresource/deploymentresource/enterprise_search_expanders_test.go
  ec/ecresource/deploymentresource/expanders.go
  ec/ecresource/deploymentresource/expanders_test.go
  ec/ecresource/deploymentresource/flatteners_test.go
  ec/ecresource/deploymentresource/kibana_expanders.go
  ec/ecresource/deploymentresource/kibana_expanders_test.go
  ec/ecresource/deploymentresource/schema.go
  ec/ecresource/deploymentresource/schema_kibana.go
  ec/ecresource/deploymentresource/update_test.go
  ec/ecresource/trafficfilterassocresource/expanders_test.go
  ec/ecresource/trafficfilterassocresource/flatteners_test.go
  ec/ecresource/trafficfilterresource/expanders_test.go
  ec/ecresource/trafficfilterresource/flatteners_test.go
  ec/internal/util/changes.go
  ec/internal/util/changes_test.go
  ec/internal/util/testutils.go
  ec/provider_config_test.go
Labels: bug

#158 testacc: Update default -parallel from 4 to 6
  build/Makefile.test
Labels: acceptance

#159 acceptance: Fix ec_deployment tests
  ec/acc/deployment_basic_defaults_test.go
  ec/acc/testdata/deployment_basic_defaults_hw_1.tf
  ec/acc/testdata/deployment_basic_defaults_hw_2.tf
Labels: acceptance
