Repository elastic/terraform-provider-ec, pull requests merged in 2020-11, with the labels that each got.

#167 ec_deployment: Support Hot Warm ILM deployments
  ec/ecresource/deploymentresource/elasticsearch_expanders.go
  ec/ecresource/deploymentresource/elasticsearch_expanders_test.go
  ec/ecresource/deploymentresource/expanders_test.go
Labels: bug

#160 ec_deployment: Stop making use of AsList field in deployment template get calls
  ec/acc/deployment_config_test.go
  ec/ecresource/deploymentresource/expanders.go
  ec/ecresource/deploymentresource/expanders_test.go
Labels: Refactor / Internal

#161 misc: Add fake-sdk and remove-fake-sdk make targets
  build/Makefile.dev
Labels: Refactor / Internal

#169 ec_deployments: Document all available statuses
  docs/data-sources/ec_deployments.md
Labels: documentation

#170 ec_deployment: Support snapshot source restore
  docs/resources/ec_deployment.md
  ec/ecresource/deploymentresource/elasticsearch_expanders.go
  ec/ecresource/deploymentresource/elasticsearch_expanders_test.go
  ec/ecresource/deploymentresource/schema_elasticsearch.go
  go.sum
Labels: enhancement

#173 [Terraform] Editing ec_deployment_traffic_filter_association.md
  docs/resources/ec_deployment_traffic_filter_association.md
Labels: documentation

#168 [Terraform] Editing index.md
  docs/index.md
Labels: documentation

#177 [Terraform] Editing data-sources/ec_deployment.md
  docs/data-sources/ec_deployment.md
Labels: documentation

#175 [Terraform] Editing data-sources/ec_stack.md
  docs/data-sources/ec_stack.md
Labels: documentation

#172 [Terraform] Editing ec_deployment_traffic_filter.md
  docs/resources/ec_deployment_traffic_filter.md
Labels: documentation

#176 [Terraform] Editing data-sources/ec_deployments.md
  docs/data-sources/ec_deployments.md
Labels: documentation

#171 [Terraform] Editing ec_deployment.md
  docs/resources/ec_deployment.md
Labels: documentation

#179 ec_deployment: Limit version to 6.6.0 or higher
  docs/resources/ec_deployment.md
  ec/ecresource/deploymentresource/elasticsearch_expanders.go
  ec/ecresource/deploymentresource/import.go
  ec/ecresource/deploymentresource/import_test.go
  ec/ecresource/deploymentresource/resource.go
  go.mod
  go.sum
Labels: documentation, enhancement

#180 ec_deployment: Remove per topology config block
  docs/resources/ec_deployment.md
  ec/acc/deployment_basic_test.go
  ec/acc/testdata/deployment_basic_settings_config_2.tf
  ec/acc/testdata/deployment_basic_topology_config_2.tf
  ec/ecresource/deploymentresource/apm_expanders.go
  ec/ecresource/deploymentresource/apm_expanders_test.go
  ec/ecresource/deploymentresource/apm_flatteners.go
  ec/ecresource/deploymentresource/apm_flatteners_test.go
  ec/ecresource/deploymentresource/elasticsearch_expanders.go
  ec/ecresource/deploymentresource/elasticsearch_expanders_test.go
  ec/ecresource/deploymentresource/elasticsearch_flatteners.go
  ec/ecresource/deploymentresource/elasticsearch_flatteners_test.go
  ec/ecresource/deploymentresource/enterprise_search_expanders.go
  ec/ecresource/deploymentresource/enterprise_search_expanders_test.go
  ec/ecresource/deploymentresource/enterprise_search_flatteners.go
  ec/ecresource/deploymentresource/expanders_test.go
  ec/ecresource/deploymentresource/flatteners_test.go
  ec/ecresource/deploymentresource/kibana_expanders.go
  ec/ecresource/deploymentresource/kibana_expanders_test.go
  ec/ecresource/deploymentresource/kibana_flatteners.go
  ec/ecresource/deploymentresource/kibana_flatteners_test.go
  ec/ecresource/deploymentresource/schema_apm.go
  ec/ecresource/deploymentresource/schema_elasticsearch.go
  ec/ecresource/deploymentresource/schema_enteprise_search.go
  ec/ecresource/deploymentresource/schema_kibana.go
  ec/ecresource/deploymentresource/testutil_datastruct.go
  go.sum
Labels: breaking change

#186 [Terraform] Editing examples/deployment_ccs/README.md
  examples/deployment_ccs/README.md
Labels: documentation

#184 [Terraform] Editing examples/README.md
  examples/README.md
Labels: documentation

#185 [Terraform] Editing examples/deployment/README.md
  examples/deployment/README.md
Labels: documentation

#187 [Terraform] Editing examples/deployment_with_init
  examples/deployment_with_init/README.md
Labels: documentation

#181 Terraform init is required before apply
  examples/README.md
  examples/deployment/README.md
  examples/deployment_ccs/README.md
Labels: documentation
