Repository elastic/terraform-provider-ec, pull requests merged in 2021-05, with the labels that each got.

#300 ec_deployments: Add size parameter to data source
  .changelog/300.txt
  docs/data-sources/ec_deployments.md
  ec/ecdatasource/deploymentsdatasource/expanders.go
  ec/ecdatasource/deploymentsdatasource/expanders_test.go
  ec/ecdatasource/deploymentsdatasource/schema.go
Labels: Team:Delivery, enhancement

#308 ec_deployment: Retry destroy on Timeout Exceeded
  .changelog/308.txt
  ec/ecresource/deploymentresource/delete.go
  ec/ecresource/deploymentresource/delete_test.go
Labels: Team:Delivery, acceptance, enhancement

#309 ec_deployment: Set snapshot restore strategy to `partial` on Update
  .changelog/309.txt
  ec/acc/deployment_fixture_test.go
  ec/acc/deployment_snapshot_test.go
  ec/acc/testdata/deployment_snapshot_1.tf
  ec/acc/testdata/deployment_snapshot_2.tf
  ec/ecresource/deploymentresource/elasticsearch_expanders.go
  ec/ecresource/deploymentresource/expanders.go
  ec/ecresource/deploymentresource/expanders_test.go
Labels: Team:Delivery, bug

#315 build: fix build to work on darwin/arm64
  build/Makefile.build
  build/Makefile.deps
  build/Makefile.tools
Labels: enhancement

#318 docs: data tiers update
  docs/resources/ec_deployment.md
Labels: documentation
