Repository elastic/terraform-provider-ec, pull requests merged in 2021-01, with the labels that each got.

#200 release: Amend make tag target to use a v prefix
  .goreleaser.yml
  build/Makefile.release
Labels: Team:Delivery, bug

#206 templates: Enrich GitHub templates with labels
  .github/ISSUE_TEMPLATE/BUG_REPORT.md
  .github/ISSUE_TEMPLATE/FEATURE_REQUEST.md
  .github/ISSUE_TEMPLATE/GENERIC_QUESTION.md
Labels: Team:Delivery, documentation

#211 testacc: limit maximum concurrent tests to 4
  build/Makefile.test
Labels: Team:Delivery, acceptance

#218 ec_deployment: Add tags key value map
  docs/resources/ec_deployment.md
  ec/acc/deployment_basic_tags_test.go
  ec/acc/testdata/deployment_basic_tags_1.tf
  ec/acc/testdata/deployment_basic_tags_2.tf
  ec/acc/testdata/deployment_basic_tags_3.tf
  ec/acc/testdata/deployment_basic_tags_4.tf
  ec/ecresource/deploymentresource/expanders.go
  ec/ecresource/deploymentresource/expanders_test.go
  ec/ecresource/deploymentresource/flatteners.go
  ec/ecresource/deploymentresource/flatteners_test.go
  ec/ecresource/deploymentresource/schema.go
  ec/ecresource/deploymentresource/testdata/deployment-aws-io-optimized-tags.json
  go.sum
Labels: Team:Delivery, enhancement

#208 ec_traffic_filter: Fix rule ordering bug
  ec/acc/deployment_traffic_filter_test.go
  ec/acc/testdata/deployment_traffic_filter_basic_update_large.tf
  ec/ecresource/trafficfilterresource/expanders.go
  ec/ecresource/trafficfilterresource/expanders_test.go
  ec/ecresource/trafficfilterresource/flatteners.go
  ec/ecresource/trafficfilterresource/flatteners_test.go
  ec/ecresource/trafficfilterresource/schema.go
  ec/ecresource/trafficfilterresource/schema_test.go
Labels: Team:Delivery, bug

#219 lint: Fix terraform fmt to return exit code > 0
  build/Makefile.lint
Labels: Refactor / Internal

#221 ci: Use a bigger worker node n1-highcpu-8
  .ci/pipelines/acceptance.Jenkinsfile
  .ci/pipelines/release.Jenkinsfile
Labels: acceptance

#220 ci: Clean acc dangling deployments on cleanup step
  .ci/pipelines/acceptance.Jenkinsfile
  CONTRIBUTING.md
  build/Makefile.test
  ec/acc/deployment_sweep_test.go
  ec/acc/deployment_traffic_filter_sweep_test.go
Labels: acceptance

#223 acc: fix ec_deployment post-destroy check
  ec/acc/deployment_destroy_test.go
Labels: Team:Delivery, acceptance

#216 ec_extension: implement extension resource
  docs/resources/ec_extension.md
  ec/acc/extension_basic_test.go
  ec/acc/extension_bundle_file_test.go
  ec/acc/extension_destroy_test.go
  ec/acc/extension_plugin_download_test.go
  ec/acc/testdata/extension_basic.tf
  ec/acc/testdata/extension_bundle_file.tf
  ec/acc/testdata/extension_plugin_download.tf
  ec/ecresource/extensionresource/create.go
  ec/ecresource/extensionresource/create_test.go
  ec/ecresource/extensionresource/delete.go
  ec/ecresource/extensionresource/delete_test.go
  ec/ecresource/extensionresource/read.go
  ec/ecresource/extensionresource/read_test.go
  ec/ecresource/extensionresource/request.go
  ec/ecresource/extensionresource/resource.go
  ec/ecresource/extensionresource/schema.go
  ec/ecresource/extensionresource/test_extension_bundle.json
  ec/ecresource/extensionresource/testutil_datastruct.go
  ec/ecresource/extensionresource/update.go
  ec/ecresource/extensionresource/update_test.go
  ec/provider.go
  examples/extension_bundle/README.md
  examples/extension_bundle/extension.tf
  examples/extension_bundle/files/content.json
  examples/extension_bundle/files/content.json.zip
  examples/extension_bundle/outputs.tf
Labels: new-resource
