Repository elastic/terraform-provider-ec, pull requests merged in 2021-02, with the labels that each got.

#235 release: Correct release version suffixes
  build/Makefile.release
Labels: Team:Delivery, bug

#241 ec_deployments: Bugfix for queries with hyphens
  ec/acc/datasource_deployment_basic_test.go
  ec/acc/testdata/datasource_deployment_basic.tf
  ec/ecdatasource/deploymentsdatasource/expanders.go
  ec/ecdatasource/deploymentsdatasource/expanders_test.go
Labels: bug

#242 ec_deployment: Fix where datasource was adding unused topology elements
  ec/acc/datasource_deployment_basic_test.go
  ec/ecdatasource/deploymentdatasource/flatteners_apm.go
  ec/ecdatasource/deploymentdatasource/flatteners_apm_test.go
  ec/ecdatasource/deploymentdatasource/flatteners_elasticsearch.go
  ec/ecdatasource/deploymentdatasource/flatteners_elasticsearch_test.go
  ec/ecdatasource/deploymentdatasource/flatteners_enterprise_search.go
  ec/ecdatasource/deploymentdatasource/flatteners_enterprise_search_test.go
  ec/ecdatasource/deploymentdatasource/flatteners_kibana.go
  ec/ecdatasource/deploymentdatasource/flatteners_kibana_test.go
Labels: bug

#244 ec_deployment : Tags for deployment datasource
  docs/data-sources/ec_deployment.md
  ec/acc/datasource_tags_test.go
  ec/acc/testdata/datasource_tags.tf
  ec/ecdatasource/deploymentdatasource/datasource.go
  ec/ecdatasource/deploymentdatasource/datasource_test.go
  ec/ecdatasource/deploymentdatasource/flatteners_tags.go
  ec/ecdatasource/deploymentdatasource/flatteners_tags_test.go
  ec/ecdatasource/deploymentdatasource/schema.go
Labels: enhancement
