Repository elastic/terraform-provider-ec, pull requests merged in 2021-03, with the labels that each got.

#257 scripts: Add changelog generator
  .changelog/208.txt
  .changelog/209.txt
  .changelog/216.txt
  .changelog/218.txt
  .changelog/235.txt
  .changelog/238.txt
  .changelog/241.txt
  .changelog/242.txt
  .changelog/244.txt
  .changelog/248.txt
  .changelog/253.txt
  .github/workflows/changelog_generation.yml
  CHANGELOG.md
  Makefile
  README.md
  build/Makefile.deps
  build/Makefile.release
  docs/index.md
  ec/version.go
  examples/deployment/deployment.tf
  examples/deployment_ccs/deployment.tf
  examples/deployment_ec2_instance/provider.tf
  examples/deployment_with_init/provider.tf
  examples/extension_bundle/extension.tf
  scripts/changelog.tmpl
  scripts/generate-changelog.sh
  scripts/release-note.tmpl
Labels: Refactor / Internal, Team:Delivery

#255 chore: Update Go and Terraform CI versions
  .ci/pipelines/acceptance.Jenkinsfile
  .ci/pipelines/release.Jenkinsfile
  .github/workflows/go.yml
Labels: Refactor / Internal, Team:Delivery

#259 mod: Update cloud-sdk-go to latest version
  go.mod
  go.sum
Labels: Team:Delivery, bug

#261 docs: Update examples to use latest available version
  examples/deployment/deployment.tf
  examples/deployment_ccs/deployment.tf
  examples/deployment_ec2_instance/elastic_deployment.tf
  examples/deployment_ec2_instance/variables.tf
  examples/deployment_with_init/deployment.tf
Labels: documentation

#260 gh issues: Update bug issue template
  .github/ISSUE_TEMPLATE/BUG_REPORT.md
Labels: Refactor / Internal

#262 docs: Update doc examples to use stack datasource
  README.md
  docs/index.md
  docs/resources/ec_deployment.md
  docs/resources/ec_deployment_traffic_filter.md
Labels: Team:Delivery, documentation

#264 ec_deployment: Add `elasticsearch.extension` block
  .changelog/264.txt
  docs/resources/ec_deployment.md
  docs/resources/ec_deployment_extension.md
  ec/acc/deployment_with_extension_bundle_test.go
  ec/acc/testdata/deployment_with_extension_bundle_file.tf
  ec/ecresource/deploymentresource/elasticsearch_expanders.go
  ec/ecresource/deploymentresource/elasticsearch_flatteners.go
  ec/ecresource/deploymentresource/expanders_test.go
  ec/ecresource/deploymentresource/flatteners_test.go
  ec/ecresource/deploymentresource/import_test.go
  ec/ecresource/deploymentresource/schema_elasticsearch.go
  ec/ecresource/deploymentresource/testdata/deployment-aws-io-optimized-extension.json
Labels: Team:Delivery, enhancement

#265 extension: Use correct API
  ec/ecresource/extensionresource/upload.go
Labels: Refactor / Internal

#266 ec_deployment: Remove resources .version subfield
  .changelog/266.txt
  docs/resources/ec_deployment.md
  ec/acc/datasource_deployment_basic_test.go
  ec/acc/deployment_basic_test.go
  ec/ecresource/deploymentresource/apm_expanders.go
  ec/ecresource/deploymentresource/apm_expanders_test.go
  ec/ecresource/deploymentresource/apm_flatteners.go
  ec/ecresource/deploymentresource/apm_flatteners_test.go
  ec/ecresource/deploymentresource/enterprise_search_expanders.go
  ec/ecresource/deploymentresource/enterprise_search_flatteners.go
  ec/ecresource/deploymentresource/enterprise_search_flatteners_test.go
  ec/ecresource/deploymentresource/expanders_test.go
  ec/ecresource/deploymentresource/kibana_expanders.go
  ec/ecresource/deploymentresource/kibana_expanders_test.go
  ec/ecresource/deploymentresource/kibana_flatteners.go
  ec/ecresource/deploymentresource/kibana_flatteners_test.go
  ec/ecresource/deploymentresource/schema_apm.go
  ec/ecresource/deploymentresource/schema_enteprise_search.go
  ec/ecresource/deploymentresource/schema_kibana.go
  ec/ecresource/deploymentresource/schema_v0.go
Labels: Team:Delivery, breaking change

#272 docs: Update registry index file and main readme
  README.md
  docs/index.md
Labels: documentation

#278 ec_deployment_extension: Support import
  docs/resources/ec_deployment_extension.md
  ec/acc/deployment_extension_basic_test.go
  ec/ecresource/extensionresource/resource.go
Labels: enhancement

#282 ec_deployment: Add note on disabling kibana
  docs/resources/ec_deployment.md
Labels: documentation

#284 release: Fix Jenkins release job
  .ci/jobs/elastic+terraform-provider-ec+tag.yml
Labels: Refactor / Internal
